//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_ASI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public Nullable<int> ID_Indicadores_Obtenidos { get; set; }
        public int ID_Diagnostico { get; set; }
        public Nullable<bool> Confirmacion_Experto { get; set; }
        public string Numero_Denuncia_Legal { get; set; }
        public Nullable<bool> Confirmacion_Legal { get; set; }
        public Nullable<bool> Sospecha { get; set; }
        public string Nivel { get; set; }
        public string Descripcion_Abordaje { get; set; }
        public string Diagnostico_Experto { get; set; }
    }
}
