//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_ASI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicadores_Obtenidos
    {
        public int ID_Indicadores_Obtenidos { get; set; }
        public Nullable<bool> Embarazo { get; set; }
        public string Rango_Etario { get; set; }
        public Nullable<bool> Restos_de_semen { get; set; }
        public Nullable<bool> ETS { get; set; }
        public Nullable<bool> Lesion_zona_genital { get; set; }
        public Nullable<bool> Enuresis { get; set; }
        public Nullable<bool> Dolores_abdominales { get; set; }
        public Nullable<bool> Encopresis { get; set; }
        public Nullable<bool> Relato_de_abuso { get; set; }
        public Nullable<bool> Conductas_sexualizadas_no_esperables { get; set; }
        public Nullable<bool> Fugas_del_hogar { get; set; }
        public Nullable<bool> Problemática_de_consumo { get; set; }
        public Nullable<bool> Conductas_autoagresivas { get; set; }
        public Nullable<bool> Retraimiento { get; set; }
        public Nullable<bool> Trastornos_del_sueño { get; set; }
        public Nullable<bool> Trastornos_alimentarios { get; set; }
        public Nullable<bool> Terrores_inexplicables { get; set; }
        public Nullable<bool> Disociación { get; set; }
        public Nullable<bool> Inflamación_zona_vaginal { get; set; }
        public string Sexo { get; set; }
    }
}
