//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_ASI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Recibido
    {
        public Nullable<int> Edad { get; set; }
        public int ID_Informe { get; set; }
        public Nullable<bool> Gestando { get; set; }
        public string Semen { get; set; }
        public Nullable<bool> Comportamiento_suicida { get; set; }
        public string Autolesiones { get; set; }
        public string Enfermedad_transm_sexual { get; set; }
        public string Lesiones_genitales { get; set; }
        public Nullable<bool> Inflamación_Vaginal { get; set; }
        public string Incontinencia_urinaria { get; set; }
        public string Dolores_de_abdomen { get; set; }
        public string Incontinencia_fecal { get; set; }
        public string Conductas_Sexualizadas { get; set; }
        public string Fugas { get; set; }
        public string Consumo_problemático { get; set; }
        public Nullable<bool> Retraido { get; set; }
        public string Problemas_al_dormir { get; set; }
        public string Problemas_alimenticios { get; set; }
        public string Terrores_sin_causa_aparente { get; set; }
        public string Desconexión_mental { get; set; }
        public string Relato { get; set; }
        public string Sexo { get; set; }
    }
}
